# Generated by Django 4.0 on 2023-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_autor_libro_delete_libreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
