# Generated by Django 4.0 on 2023-08-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_autor_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
